services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - '8000:80' # port 8000 on local machine is mapped to port 80 on the container
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php web server
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./backend:/var/www/html

  # mysql databse
  db:
    image: mysql:8.2.0
    # volumes:
    #   - mysqldata:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_php_backend
      MYSQL_USER: jaroslaw
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

# volumes:
#   mysqldata: